### ISSUE TITLE
GUI stuck when train is destroy when trying to name a new group

### ISSUE THREAD

**Issue by Teneombre** [raiguard/TrainGroups#23] opened 2023-10-03 04:54 UTC
### Description

If you are naming a new group and your train is destroy during the process, your are stuck with the naming gui, with most of the interaction not working. e and enter not working to leave the gui. It may be linked to the fact the name was actually empty when it happens.
Saving and reloading doesn't help, you are still stuck with the gui "change train group". Being unable to select a train (and any entities) make it impossible to complete the process so you need to load an earlier save :/
Can't load the save files due to files size limit

[factorio-current.log](https://github.com/raiguard/TrainGroups/files/12788687/factorio-current.log)

**Comment by raiguard** [comment] 2023-10-14 23:41
Duplicate of #22

**Closed by raiguard** 2023-10-14 23:41 UTC
